LOGDIR: ''
DEVICE: 'cuda'
OUTPUT_DIR: 'results'
NUM_WORKERS: 4
SEED_VALUE: 0
IMG_RES: 256

DATASET:
  LIST: ['3dpw_vid']
  PARTITION: [1.0]
  # LIST: ['3dpw_vid', 'h36m_vid', 'bedlam_vid']
  # PARTITION: [0.165, 0.165, 0.67]
  SEQ_LEN: 16
  TEST: '3dpw_vid_test' #'emdb_1' or '3dpw_vid_test'

LOSS:
  KPT2D: 5.0
  KPT3D: 5.0
  SMPL_PLUS: 1.0
  V3D: 1.0
  ACTION_RATE_L2: 10.0
  BETA_T: 10.0


TRAIN:
  RESUME: # if resume training, put the ckpt.pth here
  LOAD_LATEST: True
  BATCH_SIZE: 24
  MULTI_LR: True
  LR: 1e-5
  LR2: 1e-4 # NOTE(yiwen) this is for st module
  WARMUP_STEPS: 3000
  SUMMARY_STEP: 50
  VALID_STEP: 150
  SAVE_STEP: 1000
  MAX_STEP: 250000
  GAMMA: 1
  UPDATE_ITER: 1
  CLIP_GRADIENT: True
  CLIP_NORM: 1.0
  WD: 0.01
  OPT: 'AdamW'
  LOSS_SCALE: 1
 
TEST:
  BATCH_SIZE: 8 # NOTE(yiwen) don't change this batch size for a fair comparison

MODEL:
  CHECKPOINT: 'data/pretrain/hmr2b/epoch=35-step=1000000.ckpt'
  ST_MODULE: True
  MOTION_MODULE: False
  ST_HDIM: 512
  MOTION_HDIM: 384
  ST_NLAYER: 6
  MOTION_NLAYER: 6
  VALID_RANGE: (0,2)


EXP_NAME: 'try_3dpwandh36m' # onlineTRAM_sequence online_videohmrv5_actionrate12
COMMENT:
  'Default configs.'


