LOGDIR: ''
DEVICE: 'cuda'
OUTPUT_DIR: 'results'
NUM_WORKERS: 0 # 15
SEED_VALUE: 0
IMG_RES: 256

DATASET:
  # LIST: ['3dpw_vid', 'h36m_vid'] # NOTE(yiwen) temp debugging
  # PARTITION: [0.5, 0.5]
  LIST: ['3dpw_vid']
  PARTITION: [1.0]
  # LIST: ['3dpw_vid', 'h36m_vid', 'bedlam_vid']
  # PARTITION: [0.165, 0.165, 0.67]
  SEQ_LEN: 3
  TEST: '3dpw_vid_test' #'emdb_1' or '3dpw_vid_test' by default

LOSS:
  KPT2D: 5.0
  KPT3D: 5.0
  SMPL_PLUS: 1.0
  V3D: 1.0


TRAIN:
  RESUME: None
  LOAD_LATEST: True
  BATCH_SIZE: 24
  MULTI_LR: True
  LR: 1e-5
  LR2: 3e-5
  WARMUP_STEPS: 3000
  SUMMARY_STEP: 50
  VALID_STEP: 250
  SAVE_STEP: 1000
  MAX_STEP: 250000
  GAMMA: 1
  UPDATE_ITER: 1
  CLIP_GRADIENT: True
  CLIP_NORM: 1.0
  WD: 0.01
  OPT: 'AdamW'
  LOSS_SCALE: 1
 
TEST:
  BATCH_SIZE: 16

MODEL:
  CHECKPOINT: 'data/pretrain/hmr2b/epoch=35-step=1000000.ckpt'
  ST_MODULE: True
  MOTION_MODULE: False
  ST_HDIM: 512
  MOTION_HDIM: 384
  ST_NLAYER: 6
  MOTION_NLAYER: 6
  VALID_RANGE: (0,2)


EXP_NAME: 'test_debug' # shorter temporal expansion dims
COMMENT:
  'Default configs.'


